use_frameworks!

platform :ios, '13.0'

target 'SwiftUICustomSlider_Example' do
  pod 'SwiftUICustomSlider', :path => '../'

  target 'SwiftUICustomSlider_Tests' do
    inherit! :search_paths

    
  end
end
